### ISSUE TITLE
A.11.6. Returning from loop

### ISSUE THREAD

**Issue by shandysiswandi** [novalagung/dasarpemrogramanrust#29]
<img width="1013" alt="Screenshot 2023-01-08 at 01 02 43" src="https://user-images.githubusercontent.com/29152523/211164450-55aa0528-79d3-441c-a688-b366bfaba9e8.png">

apakah memang tidak di quote tulisan 0 ?
karena nilai variable yang lain juga di quote.

**Comment by novalagung** [comment]
harusnya di quote

FYI aja, ada cukup banyak potensi typo dan konten yang kurang pas, karena ebook ini masih versi alpha

**Comment by shandysiswandi** [comment]
<img width="974" alt="Screenshot 2023-01-26 at 20 45 22" src="https://user-images.githubusercontent.com/29152523/214851709-1bc9dc4a-b7bf-4e19-9fbf-1cbe93807209.png">

**Comment by shandysiswandi** [comment]
saya rasa ini pasti typo. di rust tidak ada int32,


<img width="974" alt="Screenshot 2023-01-28 at 21 24 17" src="https://user-images.githubusercontent.com/29152523/215271847-f3718dd8-27c0-4542-be04-deee48a37d7b.png">

**Comment by shandysiswandi** [comment]
kurang huruf c

<img width="959" alt="Screenshot 2023-01-28 at 22 04 59" src="https://user-images.githubusercontent.com/29152523/215273758-5755a60b-e24b-4aec-b38f-b83532527d80.png">

**Comment by shandysiswandi** [comment]
`bcrypt::hash` dari mana??

<img width="1009" alt="Screenshot 2023-01-28 at 22 23 07" src="https://user-images.githubusercontent.com/29152523/215274755-8893b83d-bbac-4cca-9ff5-7fd9ac6ac258.png">

**Comment by shandysiswandi** [comment]
apakah yang di maksud `string_to_number`?

<img width="933" alt="Screenshot 2023-01-28 at 22 26 59" src="https://user-images.githubusercontent.com/29152523/215274922-fbb641bb-61ec-4fd7-bf17-ae5089e94347.png">

**Comment by novalagung** [comment]
Feel free to create the PR for the issues 🙂

**Comment by novalagung** [comment]
> apakah yang di maksud `string_to_number`?
> 
> <img width="933" alt="Screenshot 2023-01-28 at 22 26 59" src="https://user-images.githubusercontent.com/29152523/215274922-fbb641bb-61ec-4fd7-bf17-ae5089e94347.png">
> 

Coba di test dulu aja

**Comment by novalagung** [comment]
> <img width="974" alt="Screenshot 2023-01-26 at 20 45 22" src="https://user-images.githubusercontent.com/29152523/214851709-1bc9dc4a-b7bf-4e19-9fbf-1cbe93807209.png">
> 

Ini bukan isu. Coba dibaca lagi statementnya

**Comment by novalagung** [comment]
Anyway, this issue become broader than the initial discussion. The title is invalid now. And also some of them are not issues (if you ever have the chance to try and read it carefully).

I'll break it down to multiple issues and close this one. It's better to have separate issue treated on separately.
