### ISSUE TITLE
How to see min max value in data type numbers

### ISSUE THREAD

**Issue by shandysiswandi** [novalagung/dasarpemrogramanrust#50]
if you ok, i will create PR

@novalagung 

<img width="1379" alt="Screenshot 2023-01-31 at 17 54 41" src="https://user-images.githubusercontent.com/29152523/215742363-63f07b80-7e01-472d-a71d-0bf8648c3013.png">

**Comment by novalagung** [comment]
@shandysiswandi can you elaborate more about the issue? Seeing the image, I cannot tell which part is wrong and also what is your suggestion

**Comment by shandysiswandi** [comment]
@novalagung this is not a issue, the one inside the white circle is I added a new text.

**Comment by novalagung** [comment]
Oh, my bad. Yeah I think that is a good addition. Feel free to submit the PR. Thanks!
