### ISSUE TITLE
Ask:  Operator negasi

### ISSUE THREAD

**Issue by shandysiswandi** [novalagung/dasarpemrogramanrust#53]
hi @novalagung , I'm confused with the note in this picture. 
here it says that it can be used on integer and bool data types. 
if the data type is bool or the expression that produces bool I understand, but with integers ? I do not completely understand.

<img width="997" alt="Screenshot 2023-02-01 at 13 26 35" src="https://user-images.githubusercontent.com/29152523/215968686-989f4f30-dec2-449e-80ce-fda64374b96b.png">

**Comment by novalagung** [comment]
Applying `!` to an integer triggers bitwise negation. Applying it to bool triggers logical negation.

You need to learn about bitwise operation first to understand what is bitwise negation.

That topic will be covered in a separated chapter later on
