### ISSUE TITLE
A.19.2 Rust Package

### ISSUE THREAD

**Issue by wihlarkop** [novalagung/dasarpemrogramanrust#63]
in section [Menambahkan dependency atau external crate](https://dasarpemrogramanrust.novalagung.com/basic/package-crate#-menambahkan-dependency-atau-external-crate) maybe you can add alternative way to install dependency or external crate into cargo.toml with [cargo add](https://doc.rust-lang.org/cargo/commands/cargo-add.html)

**Comment by novalagung** [comment]
@wihlarkop nice idea. will add it sometime today. thanks!
