### ISSUE TITLE
feat: `?` Operator

### ISSUE THREAD

**Issue by afifurrohman-id** [novalagung/dasarpemrogramanrust#89]
Hi @novalagung this currently is blocking ?
https://github.com/novalagung/dasarpemrogramanrust/blob/facf2baaff0578cb9f1c8bd358fe7a6d8482d020/docs/basic/result-type.md#L264-L266

This may depend on:
- [ ] `?` in Testing
- [ ]  `?` in Option
- [ ] Trait Object, `dyn` Keyword
- [ ] Smart Pointer

If some of this task is done is good to open PR.

**Comment by novalagung** [comment]
@afifurrohman-id as of now maintaining this book won't become my first priority so expect some slow response from my end.

there are a bunch of things to be added, I will also review your PR if time allows.

**Comment by novalagung** [comment]
closing this ticket in favor of https://github.com/novalagung/dasarpemrogramanrust/pull/94
