### ISSUE TITLE
add pemrograman rust lanjut 

### ISSUE THREAD

**Issue by wihlarkop** [novalagung/dasarpemrogramanrust#96]
Hi mas @novalagung 

Will you be adding a pemrograman rust lanjut in the future, similar to the pemrograman  go lanjut ?

maybe you can add like how to scrape in rust with reqwest + and scraper (https://github.com/causal-agent/scraper) or you can give example how to use rust for restful api or graphql

**Comment by novalagung** [comment]
Hi Mas @wihlarkop, absolutely, once we cover more fundamental topics on rust, it should be good to start delving into the advanced topic. The two topics you mentioned are perfect to be added there under section B.

there are still a bunch of foundation topics that I'd like to add to section A, one of which is the asynchronous & concurrency stuff on Rust.
